version: '3.8'

services:
  aleen-ai:
    build: .
    container_name: aleen-ai
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      
      # Redis Configuration
      - REDIS_URL=${REDIS_URL:-redis://redis:6380}
      
      # Evolution API Configuration
      - EVOLUTION_API_BASE_URL=${EVOLUTION_API_BASE_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_INSTANCE=${EVOLUTION_INSTANCE}
      
      # Application Configuration
      - PORT=${PORT:-9000}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    command: ["./wait-for-redis.sh", "redis", "6380", "python", "main.py"]
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - aleen-network-ai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: aleen-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - aleen-network-ai
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  aleen-network-ai:
    driver: bridge

volumes:
  redis_data:
    driver: local
